(package "flymake-dart"
         "0.1.0"
         "Flymake support for dart analyze")

(website-url "https://github.com/flymake/flymake-dart")
(keywords "tools")

(package-file "flymake-dart.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "flymake-easy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
